"""baseline schema (all v1.5.0 tables)

Revision ID: 0001_baseline
Revises:
Create Date: 2026-05-31

This baseline creates the full schema directly from the SQLAlchemy models
(``Base.metadata``) so it is guaranteed to match ``app/models.py`` exactly —
it is the Alembic equivalent of the previous ``create_all`` bootstrap. Every
subsequent change must be a NEW autogenerated revision with explicit
``op.*`` operations; do not edit this file.
"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op

from app.database import Base
from app import models  # noqa: F401 - ensure all tables register on metadata

# revision identifiers, used by Alembic.
revision: str = "0001_baseline"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    bind = op.get_bind()
    Base.metadata.create_all(bind=bind)


def downgrade() -> None:
    bind = op.get_bind()
    Base.metadata.drop_all(bind=bind)
